### ISSUE TITLE
<TresCanvas> breaks Vue.js devtools 

### ISSUE THREAD

**Issue by fla** [Tresjs/nuxt#24]
### Describe the bug

Adding a <TresCanvas> breaks the [Vue.js devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd) chrome extension (in MacOS Microsoft Edge, but probably it's the same in Chrome).

The issue is present in a new empty nuxtjs setup with just this module added, as well as in the [playground](https://github.com/Tresjs/playground).

Unfortunately you have to run the playground locally in dev mode, as the Vuejs devtools is disabled in production.

I am not sure if this issue belongs here or should be open in the tres repo.

```
backend.js:3787  Job regiserApp failed:
(anonymous) @ backend.js:3787

backend.js:3788  TypeError: Cannot read properties of undefined (reading 'ownerDocument')
    at createAppRecord (backend.js:1046:59)
    at async registerAppJob (backend.js:1016:7)
```

### Reproduction

https://github.com/Tresjs/playground

### Steps to reproduce

Run `pnpm i` followed by `pnpm dev`.
Open any page, for ex: http://localhost:3000/experiments/basic-shaders

### System Info

```shell
MacOS 13.4.1
Microsoft Edge Version 114.0
```

### Used Package Manager

pnpm

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/Tresjs/tres/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guidelines](https://github.com/Tresjs/tres/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://tresjs.org/guide).
- [X] Check that there isn't [already an issue](https://github.com/tresjs/tres/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by fla** [comment]
Sorry for this. Seems like it is related to the tres itself as I found this issue https://github.com/Tresjs/tres/issues/317
